const enum MsgType {
  PlayVideo,
  PauseVideo,
  PreviousVideo,
  NextVideo,
  PlayAll,
  PlayAllRandom,
  PauseAll,
  VideoPlayEvent,
  VideoPauseEvent,
  VideoEnd,
  DeleteVideo,
  OpenPictureInWindow,
  ToggleVolumeAdjust,
  VolumeChange,
  AudioEqChange,
  EnterPip,
  ExitPip,
  RefreshSavedBadge,
  AnalyzeSongBoundaries,
  ImportYoutubePlaylist,
  ImportYoutubePlaylistFallbackResult,
  AnalyzeImportedPlaylist,
  StopAnalyzeImportedPlaylist,
}

export default MsgType;
